# Generated by Django 5.2.15 on 2026-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrround',
            name='audio_recording',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalround',
            name='audio_recording',
            field=models.URLField(blank=True, null=True),
        ),
    ]
