# Generated by Django 5.2.15 on 2026-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0002_hrround_audio_recording_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalround',
            name='video_recording',
            field=models.URLField(blank=True, null=True),
        ),
    ]
