# Generated by Django 5.2.15 on 2026-07-08 02:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0003_technicalround_video_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrround',
            name='audio_recording',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='technicalround',
            name='audio_recording',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
    ]
