# Generated by Django 5.2.15 on 2026-08-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0007_codinground_is_result_acknowledged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrround',
            name='questions_asked',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='technicalround',
            name='eye_contact_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='technicalround',
            name='posture_metric',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='technicalround',
            name='voice_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
