# Generated by Django 5.2.15 on 2026-06-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_type',
            new_name='role',
        ),
    ]
