# Generated by Django 5.2.15 on 2026-06-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_img_url_user_resume_url_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
